<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Review\Block\Product\Review $block */


?>
<div class="reviews-buttons">
  <a class="btn-reviews" href="#"><?= __('Review (%1)', $block->escapeHtml($block->getCollectionSize())); ?></a>
  <a class="btn-add-reviews" href="#"><?= __('Leave feedback') ?></a>
</div>
