<div class="footer-contacts">
    <?php echo $this->getLayout() ->createBlock('Magento\Cms\Block\Block') ->setBlockId('footer-contact') ->toHtml(); ?>

    <div class="footer-contacts-social">
        <p><?= __('Follow us on social networks') ?></p>
        <div class="social">
            <a class="social-link facebook" href="#"><span class="icon-facebook-logo"></span></a>
            <a class="social-link google" href="#"><span class="icon-google-plus"></span></a>
            <a class="social-link twitter" href="#"><span class="icon-twitter"></span></a>
            <a class="social-link youtube" href="#"><span class="icon-youtube"></span></a>
            <a class="social-link vk" href="#"><span class="icon-vk"></span></a>
            <a class="social-link instagram" href="#"><span class="icon-instagram"></span></a>
        </div>
    </div>
</div>